# Infos

NAME = ""
AWS_ACCOUNT = ""
AWS_REGION = ""
AKEY = ""
SKEY = ""
ENVRIOMENT = ""
PREFIX = ""
DOCKER_IMAGE_TAG = ""
ECS_KEYPAIR_NAME = ""

# Autoscalling settings

MAX_INSTANCE_SIZE = "2"
MIN_INSTANCE_SIZE = "1"
DESIRED_CAPACITY = "1"
MIN_INSTANCE_SIZE_CONSUL = "1"
MAX_INSTANCE_SIZE_CONSUL = "2"
DESIRED_CAPACITY_CONSUL = "1"

# ECS
ECS_CLUSTER_NAME = ""


